name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t test-php .
    
    - name: Test application
      run: |
        docker run --name test-container -d -p 8080:80 test-php
        sleep 5
        curl http://localhost:8080 | grep "Hello"
        docker stop test-container
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_USER_PASSWORD }}
    
    - name: Push to Docker Hub
      run: |
        docker tag test-php ${{ secrets.DOCKER_USER_NAME }}/test-php:latest
        docker push ${{ secrets.DOCKER_USER_NAME }}/test-php:latest